// src/react/Scramble.tsx
import {
  type ReactHTML,
  createElement,
  FC,
  useRef,
  useState,
  useEffect,
} from "react";
import Scrambler from "@/Scrambler";

export const Scramble: FC<{
  children: string;
  elm?: keyof ReactHTML;
  props: React.HTMLProps<HTMLElement>;
  delay?: number;
}> = ({ children, elm = "span", delay, props = {} }) => {
  const [text, setText] = useState(children);
  const textRef = useRef<HTMLHeadingElement>(null);

  useEffect(() => {
    if (delay) {
      setTimeout(() => {
        new Scrambler().scramble(text, { onIteration: setText });
      }, delay);
    } else new Scrambler().scramble(text, { onIteration: setText });
  }, []);
  return createElement(elm, { ref: textRef, ...props }, text);
};

// src/vue/Scramble.vue
<template>
  <component :is="elm" ref="textRef" v-bind="props.props"><slot /></component>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import Scrambler from "@/Scrambler";

interface Props {
  elm?: keyof HTMLElementTagNameMap;
  props?: Record<string, any>;
  delay?: number;
}

const props = withDefaults(defineProps<Props>(), {
  elm: "span",
});

const textRef = ref<HTMLElement>();
onMounted(() => {
  if (props.delay) {
    setTimeout(() => {
      new Scrambler().scramble(textRef.value!.textContent!, {
        onIteration: setText,
      });
    }, props.delay);
  } else {
    new Scrambler().scramble(textRef.value!.textContent!, {
      onIteration: setText,
    });
  }
});

function setText(scrambledText: string) {
  textRef.value!.textContent! = scrambledText;
}
</script>
