// src/react/ScrambleOnHover.tsx
import { type ReactHTML, createElement, FC, useRef, useState } from "react";
import Scrambler from "@/Scrambler";

export const ScrambleOnHover: FC<{
  children: string;
  elm?: keyof ReactHTML;
  once?: boolean;
  delay?: number;
  props?: React.HTMLProps<HTMLElement>;
}> = ({ children, elm = "span", once, delay, props = {} }) => {
  const [text, setText] = useState(children);
  const { current: scrambler } = useRef(new Scrambler());
  const textRef = useRef<HTMLHeadingElement>(null);
  const isGoingOn = useRef(false);
  const called = useRef(false);
  const onMouseOver = (e: MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (called.current && once) return;
    if (isGoingOn.current) return;
    called.current = true;
    isGoingOn.current = true;

    if (delay) {
      setTimeout(() => {
        scrambler.scramble(text, {
          onIteration: setText,
          onFinished: () => {
            isGoingOn.current = false;
          },
        });
      }, delay);
    } else {
      scrambler.scramble(text, {
        onIteration: setText,
        onFinished: () => {
          isGoingOn.current = false;
        },
      });
    }
  };

  return createElement(elm, { ref: textRef, onMouseOver, ...props }, text);
};

// src/vue/ScrambleOnHover.vue
<template>
  <component
    :is="elm"
    ref="textRef"
    @mouseover="onMouseOver"
    v-bind="props.props"
    ><slot
  /></component>
</template>

<script setup lang="ts">
import { ref } from "vue";
import Scrambler from "@/Scrambler";

const props = withDefaults(
  defineProps<{
    elm?: keyof HTMLElementTagNameMap;
    once?: boolean;
    delay?: number;
    props?: Record<string, any>;
  }>(),
  {
    elm: "span",
    once: false,
  }
);

const scrambler = new Scrambler();
const textRef = ref<HTMLElement>();
let isGoingOn = false;
let called = false;

const onMouseOver = (e: MouseEvent) => {
  e.preventDefault();
  e.stopPropagation();

  if (called && props.once) return;
  if (isGoingOn) return;

  called = true;
  isGoingOn = true;

  if (props.delay) {
    setTimeout(() => {
      scrambler.scramble(textRef.value!.textContent!, {
        onIteration: (newText) => {
          textRef.value!.textContent! = newText;
        },
        onFinished: () => {
          isGoingOn = false;
        },
      });
    }, props.delay);
  } else {
    scrambler.scramble(textRef.value!.textContent!, {
      onIteration: (newText) => {
        textRef.value!.textContent = newText;
      },
      onFinished: () => {
        isGoingOn = false;
      },
    });
  }
};
</script>
