// src/react/ScrambleInView.tsx
import {
  type ReactHTML,
  createElement,
  FC,
  useRef,
  useState,
  useEffect,
} from "react";
import Scrambler from "@/Scrambler";

export const ScrambleInView: FC<{
  children: string;
  observerOptions?: IntersectionObserverInit;
  once?: boolean;
  elm?: keyof ReactHTML;
  delay?: number;
  props?: React.HTMLProps<HTMLElement>;
}> = ({
  children,
  observerOptions = {},
  once = true,
  delay,
  elm = "span",
  props = {},
}) => {
  const [text, setText] = useState(children);
  let called = useRef(false);
  const textRef = useRef<HTMLHeadingElement>(null);
  useEffect(() => {
    const scrambler = new Scrambler();
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          if (once && called.current) {
            return observer.disconnect();
          }
          if (delay) {
            setTimeout(() => {
              scrambler.scramble(text, {
                onIteration: setText,
              });
            }, delay);
          } else {
            scrambler.scramble(text, {
              onIteration: setText,
            });
          }
          called.current = true;
        }
      });
    }, observerOptions);
    observer.observe(textRef.current!);
    return () => observer.disconnect();
  }, []);
  return createElement(elm, { ref: textRef, ...props }, text);
};

// src/vue/ScrambleInView.vue
<template>
  <component :is="elm" v-bind="props.props" ref="textRef"><slot /></component>
</template>

<script lang="ts" setup>
import { ref, onMounted, onUnmounted } from "vue";
import Scrambler from "@/Scrambler";

const props = withDefaults(
  defineProps<{
    observerOptions?: IntersectionObserverInit;
    once?: boolean;
    elm?: keyof HTMLElementTagNameMap;
    delay?: number;
    props?: Record<string, any>;
  }>(),
  {
    elm: "span",
    once: true,
  }
);

const textRef = ref<HTMLElement>();
let called = false;

onMounted(() => {
  const scrambler = new Scrambler();
  const observer = new IntersectionObserver((entries) => {
    entries.forEach((entry) => {
      if (entry.isIntersecting) {
        if (props.once && called) {
          return observer.disconnect();
        }
        if (props.delay) {
          setTimeout(() => {
            scrambler.scramble(textRef.value!.textContent!, {
              onIteration: setText,
            });
          }, props.delay);
        } else {
          scrambler.scramble(textRef.value!.textContent!, {
            onIteration: setText,
          });
        }
        called = true;
      }
    });
  }, props.observerOptions);
  observer.observe(textRef.value!);

  onUnmounted(() => observer.disconnect());
});

function setText(scrambledText: string) {
  textRef.value!.textContent! = scrambledText;
}
</script>
